name: build-publish
on: 
  push:

jobs:
  Test:
    name: Test
    runs-on: ubuntu-20.04
    container: golang:1.15.6
    defaults:
      run:
        working-directory: /go/src/github.com/Ridecell/ridectl

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - run: |
          pwd
          mkdir -p /go/src/github.com/Ridecell/ridectl/
          mv /__w/ridectl/ridectl /go/src/github.com/Ridecell/ridectl/

      - name: Env check
        run: |
          echo $GOPATH

      - name: Caching
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Debugging
        run: |
          ls -la

      - name: Test
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          make dep test
          goveralls -coverprofile=gover.coverprofile -service=github-actions -repotoken=$COVERALLS_TOKEN
