name: build-publish
on: 
  push:

jobs:
  Test:
    name: Test
    runs-on: ubuntu-20.04
    #container: golang:1.15.6
    defaults:
     run:
       working-directory: /home/runner/go/src/github.com/Ridecell/

    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.6

      - run: |
          go env
          ls -la
          pwd

      - name: Debugging
        run: |
          cd /go/src/github.com/Ridecell/ridectl/ && ls -la

      - name: Test
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          cd /go/src/github.com/Ridecell/ridectl/ridectl/ && make dep test
          cd /go/src/github.com/Ridecell/ridectl/ridectl/ goveralls -coverprofile=gover.coverprofile -service=github-actions -repotoken=$COVERALLS_TOKEN
